export class SubmitTravelCardModel{
  VehicleCardPageUrl:string = ""//	行驶证 首页url
  VehicleCardSidePageUrl:string = ""//	行驶证 副页url
  VehiclePictureUrl:string = ""//车辆照片url
  CarNumber:string = ""//车牌号
  MotorcycleType:string = ""//品牌车系
  Color:string = ""//车身颜色
  Brand:string = ""//车辆品牌
  PlateColor:string = ""//车牌颜色
  EnergyType:string = ""//能源类型
  LicenseRegDate:string = ""//车辆注册日期
  InspectAnnuallyDate:string = ""//年审日期
  VehicleCardExpiryDate:string = ""//过期日期
}