export class SubmitTrafficInsuranceModel {
  Clivtaphoto: string = "";//交强险照片
  ClivateCompany: string = "";//交强险保险公司
  ClivtaexpiryStartDate: string = "";//交强险开始时间
  ClivtaexpiryDate: string = "";//交强险过期时间
  VehicleInsurancePhoto: string = "";//商业险照片
  VehicleInsuranceCompany: string = "";//商业险公司
  VehicleInsuranceExpiryDate: string = "";//商业险过期时间
  CarriersInsurancePhoto: string = "";//承运人责任保险照片
  InsureCompany: string = "";//责任险保险公司
  CarriersInsuranceExpiryDate: string = "";//承运人责任保险过期时间
}