export class NetConstants {
  static readonly NET_TAG = "Api"
  static readonly BASE_URL = "http://39.98.122.84:24000/";//https://www.wanandroid.com
  static readonly QR_BASE_URL = "https://h5.test.hnxzkj.cn";//正式-> https://h5.hnxzkj.cn
  static readonly OSSPoint = "https://hhcx-test.oss-cn-hangzhou.aliyuncs.com";//正式-> https://img.hnxzkj.cn
  static readonly TIMEOUT = 3 * 2000;
  static readonly AUTH = ""
  static readonly TOKEN = ""
}